In [44]:
### задание 1
import numpy as np
#1.1
a = np.array([i for i in range(12,24)]); print(a)
a1 = a.reshape( 2,6); print(a1)
a2 = a.reshape( 3,4); print(a2)
a3 = a.reshape( 4,3); print(a3)
a4 = a.reshape( 6,2); print(a4)
a5 = a.reshape(12,1); print(a5)
b1 = a.reshape( 2,-1); print(b1)
b2 = a.reshape( 3,-1); print(b2)
b3 = a.reshape( 4,-1); print(b3)
b4 = a.reshape(-1, 2); print(b4)
b5 = a.reshape(-1, 1); print(b5); print(b5.ndim)
# в математическом смысле b5 тоже можно считать одномерным, хотя b5.ndim дает ответ 2

#1.2
c = (np.random.normal(0,1.0,12)).reshape( 3,4); print(c.size)
c1=c.reshape(1,-1); print(c1); print(c1.size)

#1.3
a=np.arange(20,0,-2); print(a)               # формально - массив одномерный
b=np.arange(20,1,-2).reshape(1,10); print(b) # формально - массив двумерный

#1.4
a = np.zeros((2,2)); print(a)
b = np.ones((3,2)); print(b)
v = np.vstack((a,b)); print(v,v.size)

#1.5
a = np.arange(0,12); A = a.reshape(4,3); At = A.T; print(At, np.linalg.matrix_rank(At))
B = np.dot(A,At);print(B)
#Bi = np.linalg.inv(B); print(Bi)  # обратной матрицы нет для вырожденной матрицы

#1.6
np.random.seed(42)
c = np.random.randint(0,16,16)
C = c.reshape(4,4); print(C)
D = B +10*C; D_inv =np.linalg.inv(D)
print(D); print(D_inv); print(np.linalg.det(D), np.linalg.matrix_rank(D))

#1.7
i =np.where(D_inv<0); D_inv[i] = 0; print(D_inv)
i =np.where(D_inv>0); D_inv[i] = 1; print(D_inv)
E = np.where(D_inv,B,C); print(E)

[12 13 14 15 16 17 18 19 20 21 22 23]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]
2
12
[[ 1.57921282  0.76743473 -0.46947439  0.54256004 -0.46341769 -0.46572975
   0.24196227 -1.91328024 -1.72491783 -0.56228753 -1.01283112  0.31424733]]
12
[20 18 16 14 12 10  8  6  4  2]
[[20 18 16 14 12 10  8  6  4  2]]
[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 10
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]] 2
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32

In [52]:
# ЗАДАНИЕ 2
a=np.array(([1, 2, 3, 3, 1],[6, 8, 11, 10, 7])); a = a.T; mean_a = a.mean(axis=0); print(mean_a)

[2.  8.4]


In [55]:
# ЗАДАНИЕ 3
a_centered = a - np.array([mean_a]*5)
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


In [62]:
# ЗАДАНИЕ 4
a_centered_sp = np.dot(a_centered[:,0],a_centered[:,1])
print(a_centered_sp)
a_centered_sp /= (a_centered[:,0].size - 1)
print(a_centered_sp)

8.0
2.0
